# Generated by Django 5.1.4 on 2024-12-17 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_downvotes_recipe_upvotes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvoted_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
